trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJava@1
  inputs:
    version: '11'  # Cambia si usas otra versión de Java
    jdkArchitecture: 'x64'

- script: |
    javac Main.java
    java Main
  displayName: 'Compilar y ejecutar el programa Java'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Nombre de tu conexión de servicio>'
    appType: 'java'
    appName: '<Nombre de tu App Service>'
    package: '.'
